my.service:
  enabled: false
  remote-address: 192.168.0.1
  security:
    username: ugo
    password: asdasd12
    roles :
    - ADMIN
    - USER
    attrs:
      hasWriteAuthority: false
      hasReadAuthority: false
      hasDeleteAuthority: false
